name: Deploy Flask API to Virtual Machine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Deploy to Virtual Machine
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.127.145.156 << 'EOF'
          cd /home/azureuser/my_flask_api
          git pull origin master  # Pull latest changes
          nohup python3 app.py &  # Run the Flask app in the background
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
